# Generated by Django 5.2.1 on 2025-06-26 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_options_account_account_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(choices=[(1, 'Save $1,000 for your starter emergency fund'), (2, 'Pay off all debt (except the house) using the debt snowball'), (3, 'Save 3-6 months of expenses in a fully funded emergency fund'), (4, 'Invest 15% of your household income in retirement'), (5, "Save for your children's college fund"), (6, 'Pay off your home early')], default=1)),
                ('emergency_fund_goal', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15)),
                ('emergency_fund_current', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('retirement_contribution_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('has_children', models.BooleanField(default=False)),
                ('college_fund_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('college_fund_current', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mortgage_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
