# Generated by Django 5.1.4 on 2025-06-28 02:06

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_financialstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='effective_date',
            field=models.DateField(default=api.models.today, help_text='Date this balance is effective for'),
        ),
        migrations.AddField(
            model_name='debt',
            name='effective_date',
            field=models.DateField(default=api.models.today, help_text='Date this balance is effective for'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='effective_date',
            field=models.DateField(default=api.models.today, help_text='Date this transaction is effective for'),
        ),
        migrations.AlterField(
            model_name='financialstep',
            name='current_step',
            field=models.IntegerField(choices=[(1, 'Save $2,000 for your starter emergency fund'), (2, 'Pay off all debt (except the house) using the debt snowball'), (3, 'Save 3-6 months of expenses in a fully funded emergency fund'), (4, 'Invest 15% of your household income in retirement'), (5, "Save for your children's college fund"), (6, 'Pay off your home early')], default=1),
        ),
        migrations.AlterField(
            model_name='financialstep',
            name='emergency_fund_goal',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='AccountAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('old_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_date', models.DateField(help_text='Date this change is effective for')),
                ('change_reason', models.CharField(blank=True, help_text='Reason for the change', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='api.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('old_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_date', models.DateField(help_text='Date this change is effective for')),
                ('change_reason', models.CharField(blank=True, help_text='Reason for the change', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='api.debt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_description', models.CharField(blank=True, max_length=200, null=True)),
                ('new_description', models.CharField(max_length=200)),
                ('effective_date', models.DateField(help_text='Date this change is effective for')),
                ('change_reason', models.CharField(blank=True, help_text='Reason for the change', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
