# Generated by Django 5.2.4 on 2025-07-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_account_effective_date_debt_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-effective_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-effective_date', '-created_at']},
        ),
    ]
