# Generated by Django 5.2.4 on 2025-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_account_options_alter_debt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='payoff_date',
            field=models.DateField(blank=True, help_text='Expected payoff date', null=True),
        ),
    ]
