services:
  - type: web
    name: financability-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    envVars:
      - key: REACT_APP_API_URL
        value: https://financability-backend.onrender.com
      - key: REACT_APP_ORGANIZATION
        value: financibility-finFreedom 