services:
  # Backend Django API Service
  - type: web
    name: financability-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      cd backend
      gunicorn backend.wsgi:application
    envVars:
      - key: MONGODB_ATLAS_URI
        sync: false  # Set this in Render dashboard
      - key: MONGODB_NAME
        value: financability_db
      - key: SECRET_KEY
        sync: false  # Set this in Render dashboard
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: financability-backend.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings

  # Frontend React Static Site
  - type: web
    name: financability-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://financability-backend.onrender.com
