# Generated by Django 5.2.1 on 2025-05-28 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('income', models.FloatField(default=0)),
                ('rent', models.FloatField(default=0)),
                ('credit_card_debt', models.FloatField(default=0)),
                ('transportation', models.FloatField(default=0)),
                ('utilities', models.FloatField(default=0)),
                ('internet', models.FloatField(default=0)),
                ('groceries', models.FloatField(default=0)),
                ('healthcare', models.FloatField(default=0)),
                ('childcare', models.FloatField(default=0)),
                ('additional_items', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
