# Generated by Django 5.1.4 on 2025-06-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_savings_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='savings',
            field=models.JSONField(default=list),
        ),
    ]
