# Generated by Django 5.2.4 on 2025-07-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget_savings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='savings',
            new_name='savings_items',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
