# Generated by Django 5.2.4 on 2025-08-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_add_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='additional_income',
            field=models.FloatField(default=0),
        ),
    ]
